#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
#the first 10 terms will be: {1, 2, 3, 5, 8, 13, 21, 34, 55, 89}
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
#find the sum of the even-valued terms.


fibonacci = [0, 1]
for ch in fibonacci:
    if (fibonacci[-1] <= 4000000):
        fibonacci.append(fibonacci[-2] + fibonacci[-1])
    else:  
        del fibonacci[:2]
        del fibonacci[-1]
        print(fibonacci)

tot_sum = 0
for ch in fibonacci:
    if ((ch/2) == int(ch/2)):
        tot_sum = tot_sum + ch
    else:
        tot_sum = tot_sum
print(tot_sum)